name: Frontend Docker Build and Push

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Login to Nexus Docker Registry
        run: echo "${{ secrets.NEXUS_PASSWORD }}" | docker login ${{ secrets.NEXUS_REGISTRY }} -u ${{ secrets.NEXUS_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.NEXUS_REGISTRY }}/frontend:${{ github.sha }} \
            .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.NEXUS_REGISTRY }}/frontend:${{ github.sha }}