name: Frontend Docker Build and Push

on:
  push:
    branches:
      - dev

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Image Tag
        id: image
        shell: powershell
        run: |
          "tag=${{ github.sha }}" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Login to Nexus Docker Registry
        run: docker login "${{ secrets.NEXUS_REGISTRY }}" -u "${{ secrets.NEXUS_USERNAME }}" -p "${{ secrets.NEXUS_PASSWORD }}"

        # Pytest
      - name: Install test dependencies
        run: |
          pip install -r requirements-test.txt

      - name: Run pytest
        run: |
          pytest -vv

      - name: Upload Playwright traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results/
          
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.NEXUS_REGISTRY }}/frontend:${{ steps.image.outputs.tag }} .

      - name: Push Docker image to Nexus
        run: |
          docker push ${{ secrets.NEXUS_REGISTRY }}/frontend:${{ steps.image.outputs.tag }}

      - name: Verify image exists
        run: |
          docker images | Select-String "${{ steps.image.outputs.tag }}"
