name: Pipeline 2 - Frontend Deployment Preparation

on:
  workflow_run:
    workflows:
      - "Frontend Docker Build and Push"
    types:
      - completed

jobs:
  update-infra:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: self-hosted

    steps:
      - name: Checkout infra-repo
        uses: actions/checkout@v4
        with:
          repository: gswack/infra-repo
          token: ${{ secrets.PIPELINE_TOKEN }}
          ref: dev
          path: infra-repo

      - name: Verify image exists in Nexus
        shell: powershell
        run: |
          $tag = "${{ github.event.workflow_run.head_sha }}"

          $result = curl.exe `
            -u "${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}" `
            http://localhost:8082/v2/frontend/tags/list

          if ($result -notmatch $tag) {
              throw "Image frontend:$tag does not exist in Nexus"
          }

          Write-Host "Image frontend:$tag exists in Nexus"

      - name: Update frontend image tag
        shell: powershell
        run: |
            cd infra-repo
            (Get-Content kubernetes/frontend/frontend-deployment.yaml) `
            -replace 'nexus\.nexus\.svc\.cluster\.local:8082/frontend:.*', `
            'nexus.nexus.svc.cluster.local:8082/frontend:${{ github.event.workflow_run.head_sha }}' `
            | Set-Content kubernetes/frontend/frontend-deployment.yaml

      - name: Commit and push changes
        shell: powershell
        run: |
          cd infra-repo

          git config --global --add safe.directory "$pwd"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add kubernetes/frontend/frontend-deployment.yaml

          git commit -m "Update frontend image tag to ${{ github.event.workflow_run.head_sha }}"

          git push origin dev

      - name: Open Pull Request
        shell: powershell
        env:
          GH_TOKEN: ${{ secrets.PIPELINE_TOKEN }}
        run: |
          gh pr create `
            --repo gswack/infra-repo `
            --base main `
            --head dev `
            --title "Deploy frontend ${{ github.event.workflow_run.head_sha }}" `
            --body "Automated PR: update frontend image tag to ${{ github.event.workflow_run.head_sha }}"

      - name: Auto-merge Pull Request
        shell: powershell
        env:
          GH_TOKEN: ${{ secrets.PIPELINE_TOKEN }}
        run: |
          $PR_NUMBER = gh pr list `
            --repo gswack/infra-repo `
            --head dev `
            --json number `
            --jq ".[0].number"

          if (-not $PR_NUMBER) {
            throw "No open PR found for dev branch."
          }

          gh pr merge $PR_NUMBER `
            --repo gswack/infra-repo `
            --merge `
            --admin
